### ISSUE TITLE
buck use android-support-design.aar no find res

### ISSUE THREAD

**Issue by sdfzq123** [facebook/buck#367]
my project want use android support design library. my project libs buck file 

```
import re

jar_deps = []

for jarfile in glob(['*.jar']):
  name = 'jars__' + re.sub(r'^.*/([^/]+)\.jar$', r'\1', jarfile)
  jar_deps.append(':' + name)
  prebuilt_jar(
    name = name,
    binary_jar = jarfile,
  )

android_prebuilt_aar(
  name = 'support-v4',
  aar = 'support-v4-22.2.0.aar',
  visibility = [ 'PUBLIC' ],
)

android_prebuilt_aar(
  name = 'appcompat',
  aar = 'appcompat-v7-22.2.0.aar',
  visibility = [ 'PUBLIC' ],
)

android_prebuilt_aar(
  name = 'android-design',
  aar = 'design-22.2.0.aar',
  visibility = [ 'PUBLIC' ],
)

android_prebuilt_aar(
  name = 'support-v13',
  aar = 'support-v13-22.2.0.aar',
  visibility = [ 'PUBLIC' ],
)

jar_deps.append(':support-v4')
jar_deps.append(':support-v13')
jar_deps.append(':appcompat')
jar_deps.append(':android-design')

android_library(
  name = 'all-jars',
  exported_deps = jar_deps,
  visibility = [
    '//...'
  ],
)

project_config(
    src_target = ':all-jars',
)
```

my app buck file 

```
APP_CLASS_SOURCE = 'src/main/java/com/designtest/app/AppShell.java'

android_library(
  name = 'src',
  srcs =  glob(['src/main/**/*.java'], excludes = [APP_CLASS_SOURCE]),
  resources = [':res'],
  deps = [
    ':res',
    '//libs:all-jars',
  ],
  visibility = ['PUBLIC'],
)

android_library(
    name = 'application-lib',
    srcs = [APP_CLASS_SOURCE],
    resources = [':res'],
    deps = [
        # This is the android_build_config() rule that you created in Step 4.
        # If you jumped straight to Step 5 because your Android app was already
        # configured to build with Buck, then go back to Step 4 and add this rule
        # if you aren't already using an android_build_config().
      ':build-config',

      # This is the prebuilt_jar() rule that wraps buck-android-support.jar.
      '//libs:all-jars',
      ':res',
    ],
)

android_resource(
  name = 'res',
  res = 'src/main/res',
  package = 'com.designtest.app',
)

android_build_config(
    name = 'build-config',
    package = 'com.designtest.app',
)

keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)


android_manifest(
    name = 'manifest',
    skeleton = 'src/main/AndroidManifest.xml',
)

android_binary(
  name = 'app',
  manifest = ':manifest',
  keystore = ':debug_keystore',
  deps = [
    ':application-lib',
    ':res',
    ':src',
  ],
)

project_config(
  src_target = ':app',
  src_roots = ['src/main/java', 'src/main/aidl'],
)
```

but when build 

```
Using buckd.
in runMainWithExitCode
[-] PROCESSING BUCK FILES...FINISHED 0.2s
[+] BUILDING...0.1s (29/42 JOBS, 0 UPDATED)
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> //app:res...  0.0s (running generate_resource_ids[0.0s])
 |=> IDLE
[2015-07-01 15:14:12.919][error][command:092fe8d7-c1bc-49f0-9634-b9b87cbe261a][tid:103][com.facebook.buck.event.listener.LoggingBuildListener] The following resources were not found when processing app/src/main/res: 
RDotTxtEntry{idType=int, type=style, name=ThemeOverlay_AppCompat_Dark_ActionBar, idValue=0x00000000}
RDotTxtEntry{idType=int, type=string, name=appbar_scrolling_view_behavior, idValue=0x00000000}
RDotTxtEntry{idType=int, type=style, name=TextAppearance_AppCompat_Title_Inverse, idValue=0x00000000}

java.lang.RuntimeException
java.lang.RuntimeException
	at com.facebook.buck.android.aapt.MiniAapt.execute(MiniAapt.java:151)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:62)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:702)
	at com.facebook.buck.rules.CachingBuildEngine.access$4(CachingBuildEngine.java:678)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:269)
	at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:1)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

no find ThemeOverlay_AppCompat_Dark_ActionBar and so on .

I have import android support v4 v7-appcompat , v13 and design.
How can I edit my buck file?
Here my project  https://github.com/sdfzq123/DesignTest.git

**Comment by sdwilsh** [comment]
Where are those resources declared?

**Comment by sdfzq123** [comment]
ThemeOverlay.AppCompat.Dark.ActionBar  and TextAppearance.AppCompat.Title.Inverse declared in v7-appcompat
appbar_scrolling_view_behavior declared in android-support-design

**Comment by sdfzq123** [comment]
@sdwilsh BTW, I also tried to use gradle to build this app, gradle works.

**Comment by sdwilsh** [comment]
You are hitting the remaining part of #328, I believe.  We don't currently export resources, and @natthu and I aren't sure it's a good idea since it will slow down build times.  As a work around, you should declare it as a first-order dep on the libraries that need it.

Gradle works here because it happily walks all of your transitive deps, which we don't do because it turns out to slow down build times.


As an aside, your use of `glob` to declare your library rules isn't going to play well with `buckd` if you happen to add more libraries.

**Comment by reondz** [comment]
I have the same issue too.

**Comment by sdwilsh** [comment]
This will be closed by #391

**Comment by sdwilsh** [comment]
This should be resolved by the latest version of Buck.  @reondz or @sdfzq123, can you confirm that it's fixed for you?

**Comment by reondz** [comment]
@sdwilsh No, still have that error.
Can not find the R.attr.colorPrimary

**Comment by reondz** [comment]
@sdwilsh  Here is my demo project , BUCK file is under app folder.
https://github.com/reondz/Buck_aar_res_not_find

Would you help me to find out what's the problem? Thanks a lot.

**Comment by tgummerer** [comment]
@reondz your issue in the demo project is somewhat different.  Because buck doesn't include transitive dependencies for the resources, `R.attr.colorPrimary` will not be available in the `reon.me.helloworld` package, but only in the `android.support.v7.appcompat` package.  So the following diff fixes `buck build app:lib` in your project.

```diff
diff --git a/app/src/main/java/reon/me/helloworld/MainActivity.java b/app/src/main/java/reon/me/helloworld/MainActivity.java
index 4cd64ca..7301885 100644
--- a/app/src/main/java/reon/me/helloworld/MainActivity.java
+++ b/app/src/main/java/reon/me/helloworld/MainActivity.java
@@ -11,7 +11,7 @@ public class MainActivity extends AppCompatActivity {
     protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         setContentView(R.layout.activity_main);
-        int a = R.attr.colorPrimary;
+        int a = android.support.v7.appcompat.R.attr.colorPrimary;
     }
 
     @Override
```

**Comment by reondz** [comment]
So the only way to make it work is modify those R.xx.xx into xx.xx.xx.R.xx.x?

**Comment by sdwilsh** [comment]
Correct.  The resource isn't defined in `reon.me.helloworld`, and Buck doesn't do transitive dependencies (because they slow down the build).
