### ISSUE TITLE
Watchman lifecycle causes unecessary timeouts

### ISSUE THREAD

**Issue by mread** [facebook/buck#438]
We're seeing timeouts the first time watchman is started. Seems like we're starting it (Watchman.java and ListeningProcessExecutor.java) as if it acts like a short-lived process but that's not correct as it starts a server the first time you call it. Commented example below - hope this makes sense.

```
# firstly no watchman running
$ ps -ef | grep "./watchman"

$ ./watchman version
{
    "version": "3.0.0"
}

# output is complete but process is still running - this triggers Buck's timeout message "Timed out after %d ms waiting for Watchman command [%s]. Disabling Watchman."
$ ps -ef | grep "./watchman"
readm    11177     1  0 12:46 ?        00:00:00 ./watchman version

# run it again
$ ./watchman version
{
    "version": "3.0.0"
}

# this time the process exits immediately leaving the original process only - no timeout form the Buck code
[readm@rabbit watchman]$ ps -ef | grep "./watchman"
readm    11177     1  0 12:46 ?        00:00:00 ./watchman version
```

**Comment by mread** [comment]
@bhamiltoncx Could this also be the cause of the slow response times you mentioned in 3d44018978210721a8a8dc5326972bebb1ada78d? I've never seen `watchman version` or `watchman watch-project` take long enough to warrant a 10s timeout.

**Comment by bhamiltoncx** [comment]
Watchman's command line interface exits as quickly as it can whether or not it starts the daemon.

Some commands take a very long time to connect if they have to synchronously crawl the entire watch directory. Check your watchman.log.

**Comment by mread** [comment]
The command-line exits quickly but NuProcess is checking open file handles or something equally magic (according to its docs), try this with a watchman process running:

```
NuProcessBuilder processBuilder = new NuProcessBuilder(this, "/path/to/watchman", "version");
final NuProcess process = processBuilder.start();
process.waitFor(10L, TimeUnit.SECONDS);
```

then `killall watchman` and run it again.

For me, on the 2nd run it takes 10 seconds then timesout.

**Comment by bhamiltoncx** [comment]
Ah, is this on Linux? If so, which kernel?

**Comment by mread** [comment]
Yes, Fedora 20 kernel 3.19.

**Comment by bhamiltoncx** [comment]
Thanks. And what revision of Buck are you running?

**Comment by mread** [comment]
Our latest is:

commit b8fa3fa7c03a8df28deaa53ece5078d66024d1e4
Date:   Thu Sep 24 14:05:36 2015 -0700

**Comment by bhamiltoncx** [comment]
Got it! I believe this was a bug in NuProcess which I fixed in literally
the next commit to Buck (
https://github.com/facebook/buck/commit/088efce5b7e6d84a4519f538d1da9dbe799a278b
).

Could you try the latest Buck master build and see if that fixes the
problem? Sorry for the inconvenience.

2015年9月30日(水) 22:51 Matt Read <notifications@github.com>:

**Comment by bhamiltoncx** [comment]
The NuProcess fix should be this one:

https://github.com/brettwooldridge/NuProcess/commit/33c688a4c0a1031f0b3f84e175d2ab11f4250f0f

Ben

2015年10月1日(木) 8:44 Ben Hamilton <bgertzfield@gmail.com>:

**Comment by mread** [comment]
Have upgraded and tested - unfortunately it doesn't fix the issue. The test code I pasted in https://github.com/facebook/buck/issues/438#issuecomment-144429486 was run on the HEAD of master in NuProcess project itself. As far as I can see this is intended behaviour by NuProcess on both Windows and Linux - from the readme.md:

> On Linux and Windows there is no method by which you can be notified in an asynchronous manner that a child process has exited.  Rather than polling all child processes constantly NuProcess uses what we call "Soft Exit Detection".  When a child process exits, the OS automatically closes all of it's open file handles; which *is* something about we can be notified.  So, on Linux and Windows when NuProcess determines that both the STDOUT and STDERR streams have been closed in the child process, that child process is put into a "dead pool".  The processes in the dead pool are polled to determine when they have truly exited and what their exit status was.  See ``com.zaxxer.nuprocess.deadPoolPollMs``

I can see by breakpointing my pasted code that the deadPool is empty until watchman is killed.

**Comment by bhamiltoncx** [comment]
This might be a subtle problem with how Watchman daemonizes itself on
Linux. I know the intention is for the foreground process to be totally
disassociated from the daemon process, but it's possible an FD is getting
inherited.
2015年10月2日(金) 0:08 Matt Read <notifications@github.com>:

**Comment by bhamiltoncx** [comment]
I think I see what's happening. @Wez will want to take a look with me.

The pipes opened by NuProcess are inherited by the child process, but Watchman's daemonizing logic only explicitly closes (via `dup2()`) stdin, stdout, and stderr.

We'll need to update the Watchman daemonizing process to close all other FDs immediately after it becomes a daemon.

**Comment by bhamiltoncx** [comment]
Thanks for the fix, @wez! @mread, can you build watchman from the latest master and try again?

**Comment by mread** [comment]
Yep, fixes - thanks!

**Comment by bhamiltoncx** [comment]
Thanks for the report!
2015年10月6日(火) 23:29 Matt Read <notifications@github.com>:
